com_id: test_run
lib_sheet_path: /path/to/library_sheet_folder
qc_path: /path/to/qc
bcl_path: /path/to/bcl
fastq_path: /path/to/fastq
out_path: /path/to/pipeline_out
log_path: /path/to/log
config_path: /path/to/config
seq_type: Nuclei
workflow: 10x + HTO
organism: Rat
n_samples: 6
chemistry: RNA v3.1
scop_id: Cannot be read from library sheet v1
salmon_index: /path/to/rnor_splici_idx
T2G: /path/to/t2g.tsv
T3G: /path/to/t2g_3col.tsv
whitelist: /path/to/3M-february-2018.txt
pin_10x:
  220101_A00111_0001_ABCDEFGHIJ:
  - SI-TT-A1
  - SI-TT-B1
  - SI-TT-C1
  - SI-TT-D1
  - SI-TT-E1
  - SI-TT-F1
pin_hto:
  220101_A00111_0001_ABCDEFGHIJ:
  - D701
  - D702
  - D703
  - D704
  - D705
  - D706
